source :rubygems

gem 'haml'
gem 'sass'
gem 'sinatra'
# gem 'rack-flash'

gem "bluecloth"

gem "dm-core"
gem "dm-migrations"
gem "dm-validations"
gem "dm-sqlite-adapter"

gem "voidtools"


# brew install id3lib
# aptitude install libid3-dev
gem "id3lib-ruby"

# gem "thin"