---
  environment: development
  chdir: /Users/makevoid/Sites/share39
  address: home
  port: 3939
  pid: /Users/makevoid/Sites/share39/tmp/thin.pid
  rackup: /Users/makevoid/Sites/share39/config.ru
  log: /Users/makevoid/Sites/share39/log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: false